// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xamfkxpuhlbglkxzuofh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhbWZreHB1aGxiZ2xreHp1b2ZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMjYyNjUsImV4cCI6MjA3MDgwMjI2NX0.4hWcxw14o3MU9c_hr10G1ycuQDKfEMHIYd0iwKxQzro";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});